const titles = {
  ADD_USER: 'Добавить пользователя',
  CHANGE_INFO: 'Изменить данные',
  CHANGE_PASSWORD: 'Изменить пароль',
  CHAT: 'Название чата',
  CHAT_PLACEHOLDER: 'Введите название чата',
  CHAT_NAME: 'Имя в чате',
  CHAT_NAME_PLACEHOLDER: 'Введите имя, отображаемое пользователям',
  CHAT_SEARCH_PLACEHOLDER: 'Поиск',
  CREATE: 'Создать',
  CREATE_CHAT: '+ Создать чат',
  CHOOSE_CHAT: 'Выберите чат, чтобы отправить сообщение',
  DELETE_CHAT_CONFIRMATION: 'Вы уверены, что хотите удалить чат?',
  DELETE_CHAT: 'Удалить чат',
  DELETE_USER: 'Удалить пользователя',
  EMAIL: 'Почта',
  EMAIL_PLACEHOLDER: 'example@yandex.com',
  ENTER: 'Войти',
  ENTRANCE: 'Вход',
  FILE: 'Файл',
  LINK_TO_SIGN_UP: 'У меня нету аккаунта',
  LOCATION: 'Локация',
  LOGIN: 'Логин',
  LOGIN_PLACEHOLDER: 'Введите логин',
  LOGOUT: 'Выйти',
  MESSAGE: 'Сообщение',
  NAME: 'Имя',
  NAME_PLACEHOLDER: 'Введите имя',
  NEW_CHAT: 'Новый чат',
  NEW_PASSWORD: 'Новый пароль',
  NO: 'Нет, я передумал',
  OLD_PASSWORD: 'Текущий пароль',
  OLD_PASSWORD_PLACEHOLDER: 'Введите текущий пароль',
  OOPS: 'Упс',
  PAGE_NOT_FOUND: 'Страница не найдена...',
  PASSWORD: 'Пароль',
  PASSWORD_PLACEHOLDER: 'Введите пароль',
  PASSWORD_REPEAT: 'Повторите пароль',
  PASSWORD_REPEAT_PLACEHOLDER: 'Введите пароль повторно',
  PHONE: 'Телефон',
  PHONE_PLACEHOLDER: 'Ведите номер телефона',
  PRHOTO: 'Фото или Видео',
  PROFILE: 'Профиль',
  REGISTRATION: 'Регистрация',
  RENAME: 'Переименовать',
  RENAME_CHAT: 'Переименовать чат',
  REMEMBER_ALL: 'Я все вспомнил',
  RETURN_TO_CHATS: 'Вернуться к чатам',
  SAVE: 'Сохранить',
  SETTINGS: 'Настройки',
  SETTINGS_SIGN: 'Настройки >',
  SIGNUP: 'Зарегистрироваться',
  SOMETHING_WENT_WRONG: 'что-то пошло не так...',
  SURNAME: 'Фамилия',
  SURNAME_PLACEHOLDER: 'Введите фамилию',
  YES: 'Да, я уверен',
};

export default titles;
